"use client";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useState } from "react";
import { ArrowRight, EyeOff, LockKeyhole, Mail } from "lucide-react";
import { AppMark } from "@/components/orbit-nav";

export function LoginForm() {
  const router = useRouter(); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  async function signIn(event) { event.preventDefault(); setLoading(true); setError(""); const form = new FormData(event.currentTarget); const response = await fetch("/api/auth/login", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ emailId: form.get("email"), password: form.get("password") }) }); if (response.ok) router.push("/home"); else { setError((await response.json()).error || "Could not sign you in."); setLoading(false); } }
  return <div className="w-full max-w-md"><AppMark dark /><div className="mt-12"><p className="text-xs font-semibold uppercase tracking-[.2em] text-lime-300">Welcome back</p><h1 className="mt-3 text-4xl font-semibold tracking-[-.05em]">Sign in to Orbit.</h1><p className="mt-3 text-sm leading-6 text-zinc-500">Your next pair could be one event away.</p></div><form className="mt-9 space-y-4" onSubmit={signIn}><label className="block"><span className="mb-2 block text-sm font-medium text-zinc-300">Email address</span><span className="flex items-center gap-3 rounded-xl border border-white/10 bg-white/[.04] px-4 py-3.5"><Mail size={17} className="text-zinc-500"/><input name="email" type="email" placeholder="you@example.com" className="w-full bg-transparent text-sm outline-none placeholder:text-zinc-600" required /></span></label><label className="block"><span className="mb-2 flex justify-between text-sm font-medium text-zinc-300">Password <a href="#" className="font-normal text-lime-300">Forgot password?</a></span><span className="flex items-center gap-3 rounded-xl border border-white/10 bg-white/[.04] px-4 py-3.5"><LockKeyhole size={17} className="text-zinc-500"/><input name="password" type="password" placeholder="••••••••" className="w-full bg-transparent text-sm outline-none placeholder:text-zinc-600" required/><EyeOff size={17} className="text-zinc-600"/></span></label>{error && <p className="text-sm text-red-300">{error}</p>}<button disabled={loading} className="flex w-full items-center justify-center gap-2 rounded-xl bg-lime-300 px-5 py-3.5 text-sm font-bold text-black disabled:opacity-70">{loading ? "Signing in…" : "Sign in"}<ArrowRight size={17}/></button></form><p className="mt-8 text-center text-sm text-zinc-500">New to Orbit? <Link href="/signup" className="font-medium text-lime-300">Create an account</Link></p></div>;
}
