"use client";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useState } from "react";
import { ArrowRight, Check, LockKeyhole, Mail, UserRound } from "lucide-react";
import { AppMark } from "@/components/orbit-nav";

export function SignupForm() {
  const router = useRouter(); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  async function signUp(event) { event.preventDefault(); setLoading(true); setError(""); const form = new FormData(event.currentTarget); const [firstName, ...lastName] = String(form.get("name")).trim().split(/\s+/); const response = await fetch("/api/auth/signup", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ firstName, lastName: lastName.join(" "), emailId: form.get("email"), password: form.get("password"), age: 18, role: "buyer" }) }); if (response.ok) router.push("/home"); else { setError((await response.json()).error || "Could not create your account."); setLoading(false); } }
  const fields = [[UserRound,"Full name","Aayush Kumar","text","name"],[Mail,"Email address","you@example.com","email","email"],[LockKeyhole,"Password","At least 8 characters","password","password"]];
  return <div className="w-full max-w-md"><AppMark dark /><div className="mt-10"><p className="text-xs font-semibold uppercase tracking-[.2em] text-lime-300">Join the orbit</p><h1 className="mt-3 text-4xl font-semibold tracking-[-.05em]">Get closer to the drop.</h1><p className="mt-3 text-sm leading-6 text-zinc-500">Create your buyer account and get fair access to the things you want.</p></div><form className="mt-8 space-y-3" onSubmit={signUp}>{fields.map(([Icon,label,placeholder,type,name]) => <label className="block" key={label}><span className="mb-1.5 block text-sm font-medium text-zinc-300">{label}</span><span className="flex items-center gap-3 rounded-xl border border-white/10 bg-white/[.04] px-4 py-3"><Icon size={17} className="text-zinc-500"/><input name={name} type={type} placeholder={placeholder} className="w-full bg-transparent text-sm outline-none placeholder:text-zinc-600" required/></span></label>)}<p className="flex items-start gap-2 text-xs leading-5 text-zinc-500"><span className="grid h-4 w-4 shrink-0 place-items-center rounded border border-lime-300 bg-lime-300 text-black"><Check size={11} strokeWidth={3}/></span>I agree to Orbit&apos;s Terms of service and Privacy policy.</p>{error && <p className="text-sm text-red-300">{error}</p>}<button disabled={loading} className="flex w-full items-center justify-center gap-2 rounded-xl bg-lime-300 px-5 py-3.5 text-sm font-bold text-black disabled:opacity-70">{loading ? "Creating account…" : "Create account"}<ArrowRight size={17}/></button></form><p className="mt-7 text-center text-sm text-zinc-500">Already have an account? <Link href="/login" className="font-medium text-lime-300">Sign in</Link></p></div>;
}
